import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'category',
      label: 'Quick Start',
      items: [
        'quick-start/introduction',
        'quick-start/installation',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        {
          type: 'category',
          label: 'Configuration desgin',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core-concepts/configuration-design',
            },
          ]
        },
        {
          type: 'category',
          label: 'Resources',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core-concepts/resources',
            },
          ]
        },
        {
          type: 'category',
          label: 'Connectivity',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core-concepts/connectivity',
            },
          ]
        },
        {
          type: 'category',
          label: 'Security',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core-concepts/security',
            },
          ]
        },
        {
          type: 'category',
          label: 'Operations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core-concepts/operations',
            },
          ]
        },
        {
          type: 'category',
          label: 'Observability',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core-concepts/observability',
            },
          ]
        },
      ]
    },

    'faq',
  ],
};

export default sidebars;
